### ISSUE TITLE
Release notes for new update?

### ISSUE THREAD

**Issue by brainmaniac** [QuickBlox/q-municate-web#101]
Hello an thanks for this open source code!

I wonder is there an update coming soon and if so is there any release notes for that yet?

**Comment by Vladlukhanin** [comment]
Hello, @brainmaniac !
Yes, we have new update but we wait for other platforms releases (iOS & Android).

Added:
* Video/audio attachments;
* voice messages;
* ability to clear history after leave dialog;

Updated:
* chat's UI;
* URL preview (special design for image's URL);
* new attachments displaying (read metadata to define image or video rotate);

Fixed:
* block sending unavailable attachment type;
* show alert if global search find nothing;
* remove URL from attachment parameters;
* UI's bugs;
* other bug.

I hope that we'll make update on this week.

**Comment by brainmaniac** [comment]
Ok perfect! Thank you. We are building a sweet site with your code! Thank you :)

**Comment by Vladlukhanin** [comment]
@brainmaniac , Hello! New version in the master branch.
https://github.com/QuickBlox/q-municate-web/releases/tag/v1.11.0
