### ISSUE TITLE
Grunt build time

### ISSUE THREAD

**Issue by brainmaniac** [QuickBlox/q-municate-web#102]
**Environment details**
win 10, chrome, latest release of QM

The grunt build time is currently at 37:46s. I am building around 60 -80 times a day... That lands me on a estimated hour of waiting. Do you have any tips of how to make this shorter while in dev-mode? Unnecessary stuff to comment out? Or perhaps something else?

**Comment by Vladlukhanin** [comment]
For develop I use command **grunt serve**. This command start QM on localhost and watch for your code in real time, after any changes in code I reload page in browser. We use the **grunt build** only for deploy the last versions

**Comment by brainmaniac** [comment]
*embarassed* Thank you.....

**Comment by brainmaniac** [comment]
It turns out I have a problem with grunt serve as well. Pulled a fresh copy for this test.
```
grunt watch
    Waiting...
    //all is fine

grunt serve
    Running "serve" task
    Running "sass:dist" (sass) task
    ...
    Running "watch" task
        Waiting...
        (node:29289) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3
        // serve command is still running (not sure if it works)
```

updated enviroment:
Ubuntu 16.04.1 vagrant/virtual box in windows 10
npm 3.10.8
grunt-cli v1.2.0
grunt v1.0.1

Thanks alot for helping us out!

**Comment by Vladlukhanin** [comment]
Try to update your [nodejs](https://nodejs.org/en/download/current/) and npm (4.4.4).
I'll wait for your response.

**Comment by brainmaniac** [comment]
That fixed it. Thanks mate, this is awesome! I had first to old npm and then 4.5.4 which is latest stable but still in prerelease.
