### ISSUE TITLE
Production Deploy 

### ISSUE THREAD

**Issue by wondersoftheworld** [QuickBlox/q-municate-web#103]
Hello,
Thanks for making this.
Any guide on how to deploy to own server like digitalocean or amazon or heroku?
I have it installed on localhost.
Thanks.

**Comment by dimaspirit** [comment]
Hi, it depends on service. Q-municate is the simple client-side app, so it will not be hard.
For example, http://quickblox.github.io/quickblox-javascript-sdk/samples/chat/ this is copy based on master branch on GitHub.

**Comment by wondersoftheworld** [comment]
thanks for your response. 
1. i'd like to host it on digitalocean.

2. so, the frontend is this: https://github.com/QuickBlox/q-municate-web
and after user registers and signs in, he sees this:  http://quickblox.github.io/quickblox-javascript-sdk/samples/chat  ?

3. i have tried to login into the apps (android and ios) and have put in my phone number and verified. each time i go back to the app, i am presented with the same page asking me to enter my phone number again and going through the whole process again.
once my phone number is verified, how do i login to the app without reverifying?

thanks.

**Comment by Vladlukhanin** [comment]
Hi, @wondersoftheworld 

The best way to deploy the Web Q-municate will be start [grunt build](https://github.com/QuickBlox/q-municate-web/blob/master/README.md#6-build-and-run) and then you will have **dist** directory, this directory contains builded and minified version of the Web Q-municate application, which ready for deploy where you want.
You can host it on digitalocean and you must ask it to digitalocean support or find this solution in the internet. Sorry, but we can help you with something, that related to the Web Q-municate application, we can't advise you about where hosted you website.

**Comment by wondersoftheworld** [comment]
ok vlad, thanks.

**Comment by wondersoftheworld** [comment]
does your hosted solution provide hosting for the web q-municate app?

**Comment by Vladlukhanin** [comment]
It's solution how to prepare Q-municate for deploy
