### ISSUE TITLE
j and l

### ISSUE THREAD

**Issue by brainmaniac** [QuickBlox/q-municate-web#105]
Hello,

simple question:

What does j and l stand for in class-names?

**Comment by Vladlukhanin** [comment]
Hi, @brainmaniac !
I'm not first developer, who works with qmunicate) so, this is not for all cases... In our team we dicided to use "j-..." as class which determine DOM elemenets in JS code, this selector helps as to understand quickly what we see)
Have a good day!

**Comment by brainmaniac** [comment]
Ok, thank you
