### ISSUE TITLE
Bad init

### ISSUE THREAD

**Issue by ajthinking** [QuickBlox/q-municate-web#106]
I have a issue where the web app fails to initialize correctly.
The last outputs in the logs are

[Q-MUNICATE debug mode]:c62cc2fb.build.js:19
	QB init Object { app: Object }  c62cc2fb.build.js:19:11974
[Q-MUNICATE debug mode]:c62cc2fb.build.js:19
	App init Object { ... }  c62cc2fb.build.js:19:11974
[Q-MUNICATE debug mode]:c62cc2fb.build.js:19
	Materialize connected  c62cc2fb.build.js:19:11783

We cant pinpoint a change where the error was introduced. 
Code is just a couple of commits from the latest QM version - but no core is changed.
Error comes and goes. Reinstalling, walking up/down in the branches helps sometimes, sometimes not.
Another clue might be when I enabled SSL on the server two user browsers (FF) reacted differently:
person 1 SSL off OK!
person 2 SSL off error!
person 1 SSL on error!
person 2 SSL on OK!

Ideally one would get an error message or warning from the init methods assuming I did something wrong in my code? I have tracked the init methods of main.js, app.js, qbApiCalls into the SDK but was not able to grasp where it fails and if it is a bug or my own fault. In desperate need of pointers.
Thank you!

**Comment by Vladlukhanin** [comment]
Hi, @ajthinking 
Can you give us an error from console? Is error only on FF browser?

**Comment by ajthinking** [comment]
There is no error in the console. The last three rows output are posted above which shows App did init (!). Its not only FF, also chrome latest versions. Addons disabled, popups allowed etc so all should be good on that side.

Usually I would expect the next messages to follow: 
[ServiceProxy] Response:  Object
QB SDK: Users is found Object
etc but they do not show up even though the app should have initiated.

Checking the network tab gives no clues (all 200's).
So somewhere it is stopping the unwrapping of the app and Im stranded at the preloader screen. I cant find why/where it is stopping. Maybe check where SDK or App would output "[ServiceProxy] Response:  Object" ? Thats would be the next log message.

**Comment by Vladlukhanin** [comment]
I think that the problem may be with old data, which need for autologin. Qmunicate save some data in browser's localStorage to use them later. Try to clear local/session storage, cookie and other cache. Or may be you have had a critiacal error when connected to chat and qmunicate did relaod page in this case; so you can turn on "preserve log" to see what have happened before reloading.

**Comment by ajthinking** [comment]
So I did localStorage.clear(), empty cache and all other site specific data with no effect.
Preserving the log does not show any signs of reloading either.

**Comment by Vladlukhanin** [comment]
Can you reproduse this error when you develop on https://localhost:{PORT} (using command "grunt serve")? Or is this error just on your host server?

**Comment by ajthinking** [comment]
Error was totally on my side, bad cache combined with html edits. Closing this. Thanks for the support!

**Comment by Vladlukhanin** [comment]
Thanks for response! Have a good day!
