### ISSUE TITLE
canvas to blob is not a function

### ISSUE THREAD

**Issue by nimblemo** [QuickBlox/q-municate-web#107]
**Environment details**
Ubuntu 16.10; QB 1.11.0

**Did this work before?**
No

**Expected behavior**
Crop and attach image to chat

**Actual behavior**
image cant attached

**Logs**

```
Uncaught TypeError: canvas.toBlob is not a function
    at attach.js:67
    at Function.loadImage.transform (load-image.js:88)
    at Function.loadImage.onload (load-image.js:101)
    at HTMLImageElement.img.onload (load-image.js:27)
```

In this decision used [this polyfil - Canvas to Blob](https://github.com/blueimp/JavaScript-Canvas-to-Blob/blob/master/js/canvas-to-blob.js), but i can't understand why it don't work

**Comment by Vladlukhanin** [comment]
Hi, @thisroot 

Already fixed: https://github.com/QuickBlox/q-municate-web/commit/39e9d7ab4936d276f22daf0602fe1a4a47dd9983

Just need to use "2.7.0", not "^2.7.0" and rebuild app (bower install after fix). It has been workaround, I'll try to find a better way in next time.

**Comment by nimblemo** [comment]
Thanks, it's work!
