### ISSUE TITLE
language localization

### ISSUE THREAD

**Issue by nimblemo** [QuickBlox/q-municate-web#108]
Where find text string, "Video" and "Call" =>  "Исходящее Video Call, 00:00:01", that would change it on a string on Russian language
![2](https://cloud.githubusercontent.com/assets/8470244/26247925/be233c8c-3ca8-11e7-9caa-346fdf78bc04.png)

**Comment by Vladlukhanin** [comment]
https://github.com/QuickBlox/q-municate-web/blob/master/app/scripts/views/message.js#L270
https://github.com/QuickBlox/q-municate-web/blob/master/app/scripts/views/message.js#L272

**Comment by nimblemo** [comment]
Thanks!
