### ISSUE TITLE
incorrect behavior

### ISSUE THREAD

**Issue by nimblemo** [QuickBlox/q-municate-web#109]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/q-municate-web/issues)*

**Environment details**
*(Operating system, browser information, QM version)*
OS: Ubuntu 16.10, QB: 1.11.0

**Did this work before?**
No

**Expected behavior**
Alert message

**Actual behavior**
View activity indicator

**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*

```
[Q-MUNICATE debug mode]:
helpers.js:259 {"errors":{"login":["has already been taken."]}}
qbApiCalls.js:259 Uncaught TypeError: Cannot read property '0' of undefined
    at qbApiCalls.js:259
    at quickblox.min.js:39
    at i.handleResponse (quickblox.min.js:42)
    at Object.error (quickblox.min.js:42)
    at p (quickblox.min.js:40)
    at Object.fireWith [as rejectWith] (quickblox.min.js:40)
    at n (quickblox.min.js:41)
    at XMLHttpRequest.<anonymous> (quickblox.min.js:41)
```

**Comment by Vladlukhanin** [comment]
{"errors":{"login":["has already been taken."]}}

If you use login - try to create user with other

**Comment by nimblemo** [comment]
Просто тут приложение зависает в случае если логин уже занят. Я конечно могу сам отдебажить и исправить, но может такое некорректное поведение, Вам бы захотелось исправить в своей ветке?

**Comment by Vladlukhanin** [comment]
Дело в том что мы не используем логины... Сейчас мы создаем нового юзера через facebook или twittre digits (номер телефона). Как вариант, при возникновении такой ошибки - просто показать юзеру, что логин занят, что бы он попробовал новый. Если я вас правильно понял...

Если же эта ошибка воспрозводится в версии с master или develop ветки, в которой ничего не менялось, то вы можете описать как баг, тогда мы постараемся исправить

**Comment by nimblemo** [comment]
хорошо, понял Вас
