### ISSUE TITLE
serve time grunt serve

### ISSUE THREAD

**Issue by brainmaniac** [QuickBlox/q-municate-web#111]
**Environment details**
*(Operating system, browser information, QM version)*
Mac OSX Sierra

Quick question. What serve-time is normal for the web app? Am using the grunt serve as it comes when cloning this repo and I am at around 20 - 25 s? Is this normal or should it be faster?

Thank you!

**Comment by Vladlukhanin** [comment]
I use "grunt serve" only for developing without any cloning before, just use this command on local project. And use "grunt build" to minimize all project to prepare it for deploy.
["grunt serve"](https://github.com/QuickBlox/q-municate-web/blob/master/Gruntfile.js#L288) isn't heavier than ["grunt build"](https://github.com/QuickBlox/q-municate-web/blob/master/Gruntfile.js#L309)

"grunt serve" is about 5-10 sec and "grunt build" take more than 20 sec (20-40)

PC: Win10 (64bit), core i5-6400, 16Gb RAM
