### ISSUE TITLE
Cant attach images

### ISSUE THREAD

**Issue by ajthinking** [QuickBlox/q-municate-web#112]
Pulled a fresh copy, added configs, tried to send an image attachment.

```
87cce1dd.build.js:13 Uncaught TypeError: a.toBlob is not a function
    at 87cce1dd.build.js:13
    at Function.b.transform (87cce1dd.build.js:13)
    at Function.b.onload (87cce1dd.build.js:13)
    at HTMLImageElement.f.onload (87cce1dd.build.js:13)
```

- Enviroment: windows, mac, ubuntu with chrome, safari, firefox (all have the same error)
- Images tested: typically small png or jpg
- Content section in dashboard is not populated
- Other content like .mp3 or .txt works fine it seems to be only images
- "blueimp-load-image" and "blueimp-canvas-to-blob" are present in bower components

**Comment by Vladlukhanin** [comment]
@ajthinking, thanks for a good description of the problem =)
The same resolved issue [here](https://github.com/QuickBlox/q-municate-web/issues/107)
