### ISSUE TITLE
Contact request on offline

### ISSUE THREAD

**Issue by bytes-lab** [QuickBlox/q-municate-web#118]
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/q-municate-web/issues)*

**Environment details**
*(Operating system, browser information, QM version)*
ubuntu
firefox/chrome

**Did this work before?**

**Expected behavior**
user A sent a contact request to user B while B is offline.

B comes online and he cannot accept the request.

**Actual behavior**

**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by Vladlukhanin** [comment]
Tested on [qmunicete v.1.13.0](https://qmdev.quickblox.com/) - all are fine...

**Comment by bytes-lab** [comment]
Hi Vladlukhanin
I also use v1.13.0 and still see the issue.

Can we have a screen share session for it?
My skype id is jason.5001001 and email is jason.5001001@gmail.com

**Comment by Vladlukhanin** [comment]
Hi, @IT-corridor 
We know about this issue.
The problem will be if one condition is - the user B is already online from other PC or device.
When user B becomes online he doesn't get a presence about incoming requet from the chat server. It's XMPP server issue.
We'll fix this problem. 

If you are client of Quickblox, you will be able to ask [our support team](https://quickblox.com/contact/)

**Comment by Vladlukhanin** [comment]
@IT-corridor 
The [latest QM release](https://github.com/QuickBlox/q-municate-web/releases/tag/v1.14.0) hasn't this issue.
