### ISSUE TITLE
grunt build fails

### ISSUE THREAD

**Issue by ghost** [QuickBlox/q-municate-web#3]
I'm trying to build the project using grunt and am having issues.  My company just purchases a quickblox enterprise package and i'd like to begin working with this repo.  Any help is appreciated.  I can run the project from the /dist as it appears in the repo, but if I try to build it with grunt, the build fails.  thanks for the help.

![image](https://cloud.githubusercontent.com/assets/1727104/6041433/ec1c4d58-ac41-11e4-8f03-33b543b622bc.png)

If I use grunt --force, here is the error message

![image](https://cloud.githubusercontent.com/assets/1727104/6041452/29cca936-ac42-11e4-8229-7cbffdcab269.png)

**Comment by alexbassy** [comment]
Can you tell me which steps you took for this to happen? I just tried it and it's working fine for me (Mac OS 10.10.2)

``` bash
git clone https://github.com/QuickBlox/q-municate-web.git
cd q-municate-web
npm install
grunt build
```

**Comment by alexbassy** [comment]
Can you tell me which steps you took for this to happen? I just tried it and it's working fine for me (Mac OS 10.10.2)

```bash
git clone https://github.com/QuickBlox/q-municate-web.git
cd q-municate-web
npm install
grunt build
```

**Comment by ghost** [comment]
: ~/projects/sg/q-municate-web $grunt build
Running "clean:dist" (clean) task

> > 3 paths cleaned.

Running "compass:compile" (compass) task
directory app/.css/ 
directory app/.css/modules/ 
   create app/.css/base.css (0.05s)
   create app/.css/layouts.css (0.022s)
   create app/.css/main.css (0.279s)
   create app/.css/modules/buttons.css (0.005s)
   create app/.css/modules/chat.css (0.004s)
   create app/.css/modules/contact.css (0.015s)
   create app/.css/modules/form.css (0.004s)
   create app/.css/modules/list.css (0.003s)
   create app/.css/modules/message.css (0.005s)
   create app/.css/modules/popup.css (0.007s)
   create app/.css/modules/profile.css (0.013s)
   create app/.css/modules/smiles.css (0.009s)
   create app/.css/modules/spinner.css (0.004s)
   create app/.css/modules/text.css (0.003s)
   create app/.css/modules/webrtc.css (0.006s)
   create app/.css/modules.css (0.086s)
   create app/.css/reset.css (0.002s)
   create app/.css/states.css (0.005s)
Compilation took 0.542s

Running "createDefaultTemplate" task

Running "handlebars:compile" (handlebars) task

> > Destination not written because compiled files were empty.
> > 0 files created.

Running "requirejs:dist" (requirejs) task

> > Error: Error: ENOENT, no such file or directory '/Users/xxx/projects/sg/q-municate-web/app/bower_components/jquery/dist/jquery.js'
> > In module tree:
> >     main
> > 
> > ```
> > at Object.fs.openSync (fs.js:438:18)
> > ```
> > 
> > Warning: Task "requirejs:dist" failed. Use --force to continue.

Aborted due to warnings.

Execution Time (2015-02-04 15:01:40 UTC)
loading tasks     2.4s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 44%
compass:compile   2.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 51%
requirejs:dist   221ms  ▇▇▇▇ 4%
Total 5.5s

**Comment by alexbassy** [comment]
Can you also run 

```
bower install
```

?

**Comment by ghost** [comment]
bower Chroma-Hash#~1.0.1                             ECMDERR Failed to execute "git ls-remote --tags --heads git@github.com:mattt/Chroma-Hash.git", exit code of #128

Additional error details:
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by alexbassy** [comment]
Please follow the instructions in the first answer here: http://stackoverflow.com/a/21790275/2749986

**Comment by ghost** [comment]
hey alex, this seemed to fix it for me  https://github.com/Ecodev/typo3-cms-speciality-distribution/issues/87#issuecomment-37632016

thanks for the help.  I'm really impressed with the product so far, can't wait to dig deeper into it.  thanks
