### ISSUE TITLE
How i do  grunt build

### ISSUE THREAD

**Issue by devwill** [QuickBlox/q-municate-web#5]
Everything is instaled but not working "grunt build"

**Comment by soulfly** [comment]
What do you get?

**Comment by devwill** [comment]
this 
![captura de tela 2015-03-14 as 15 21 45](https://cloud.githubusercontent.com/assets/6561805/6652864/0da2c2fc-ca5d-11e4-9dc3-96c6578fd62c.png)

**Comment by devwill** [comment]
everytime!

**Comment by devwill** [comment]
I am wanting to point to my server quikblox but not working

**Comment by alexbassy** [comment]
Please install compass

```
$ gem install compass
```

**Comment by devwill** [comment]
now after the build broke the page, there is something else that must be done, the files generated by npm install should also be sent to the server?
![captura de tela 2015-03-15 as 11 34 07](https://cloud.githubusercontent.com/assets/6561805/6656364/ae006228-cb06-11e4-8bf3-654edffd4b77.png)

**Comment by SimonMuraya** [comment]
### If Your Using Windows, (After Installing Ruby and compass)....
1. Open Menu...
2. Click "All Programs"...
3. Select Ruby x.x.x....
4. Click "Start Command Prompt With Ruby"

### On the Command Prompt...
- Go to the directory of your app, and run "grunt build"...
- After it has finished with no warnings or errors, Run "grunt serve"
