### ISSUE TITLE
Is web app working?

### ISSUE THREAD

**Issue by schaternik** [QuickBlox/q-municate-web#55]
Hi there,

I'm trying to use your [demo web app](https://qm.quickblox.com/). I've already registered through mobile app (android) which is working. But there is no such behavior in this web demo.
So the question: is it working at all?
And what I'm doing wrong?

Thank you in advance for your response.
![screenshot from 2016-05-16 12 01 49](https://cloud.githubusercontent.com/assets/11872253/15285236/a54915cc-1b5e-11e6-96ff-0cad6a2e2ed4.png)

cc @Vladlukhanin

**Comment by Vladlukhanin** [comment]
Hi, Nastia.

Could you show the console log?

**Comment by schaternik** [comment]
@Vladlukhanin 

I'm not sure what are you asking about but it's **your** deployment of the app (look at the URL). You've pointed this URL here - https://github.com/QuickBlox/q-municate-web#live-demo
The browser network console (see screenshot) and nothing else happen.
![screenshot from 2016-05-16 15 56 02](https://cloud.githubusercontent.com/assets/11872253/15290101/f2b17aaa-1b7e-11e6-94ea-195e3d519d0d.png)

**Comment by Vladlukhanin** [comment]
https://qm.quickblox.com/ - our PROD version.
https://qmdev.quickblox.com/ - our DEV version.
All works. Please, turn off block extension in you browser and try again. (https://gyazo.com/dbc98426ddf257551464c56433eb7cc3)

**Comment by schaternik** [comment]
@Vladlukhanin 

it seems the problem in using q-municate on Firefox, i was able to login using Chromium.

UPD when I turn off uBlock Origin - it also works in Firefox

so thank you for your help
