### ISSUE TITLE
The app folder not working

### ISSUE THREAD

**Issue by robi10101298** [QuickBlox/q-municate-web#6]
Hi! The app folder don t work... Only the Dist folder, that doesn t allow me to login into the app works.. What should I do?

**Comment by soulfly** [comment]
Try to use "quickblox": "1.7.3", not the latest in bower.json

**Comment by bimwebapp** [comment]
Where can I get 1.7.3? I have the same problem, the /dist folder does not exist and the index redirects to /dist
