### ISSUE TITLE
Waiting for offlinejs.com

### ISSUE THREAD

**Issue by EmersonFJ** [QuickBlox/q-municate-web#7]
Do you know why I might be getting a "Waiting for offlinejs.com" message while trying to grunt serve?

I get that message and Qmunicate is not responsive for ~15 seconds, after which login, FB login, and signin button do not work. 

I am using quickblox 1.7.3.

**Comment by soulfly** [comment]
Where did you get this message? can you post some screenshots

**Comment by SimonMuraya** [comment]
http://github.hubspot.com/offline/docs/welcome/

**Comment by SimonMuraya** [comment]
OnlineJS is one of the many dependencies that q-municate uses to determine status of internet connection. Ever noticed a popup on q-municate platform when you don't have reliable internet connection??, check the image below

![onlinejs-2](https://cloud.githubusercontent.com/assets/10367458/9082177/df1e1f7e-3b6a-11e5-869c-a410288f0cd4.png)

However it sometimes fails or delays to connect to the service for a number of reasons related to individual internet connection and as a result fails to load the rest of the modules well.

![onlinejs](https://cloud.githubusercontent.com/assets/10367458/9081995/9baa98c2-3b69-11e5-9d6a-a898f137c4cb.png)

As commented earlier you can use https://github.com/HubSpot/offline instead. Use it, test it and please provide a feedback.
