### ISSUE TITLE
The app stay charging and cant log in.

### ISSUE THREAD

**Issue by Loborro** [QuickBlox/q-municate-web#79]
_Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/q-municate-web/issues)_

**Environment details**
_(Operating system, browser information, QM version)_
Mac OX Yosemite 10.10.5, Opera 39.0 and Google Chrome 52.0.2743.116

**Did this work before?**
Yes, when i was working 6 months ago i can run, login, and videochat without problems.

**Expected behavior**
I run the aplication expecting  that works fine.

**Actual behavior**
I run the aplication and in the menu of login, the buttons "log in" and "do you already have and acount" dont work. And i download the new source code and make the corresponding configurations and when i run "grunt build" the page charge in opera and loading remains unchanged. 

**Logs**
_(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))_

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by Vladlukhanin** [comment]
Hi, @Loborro 

For Chrome press F12 (or Ctrl + Shift + I) for Opera - Ctrl+Shift+I, and then save a printscreen with error messages. Give us this information so we can help.

**Comment by Loborro** [comment]
Hi, this screen captures are from the source code of q-municate that i was working since 2015, the app is personalized the source code is intact, and the finally captures are whit the new source code for the web app:

Grunt build without errors:
![captura de pantalla 2016-08-17 a las 13 14 49](https://cloud.githubusercontent.com/assets/11675323/17827313/58eda724-6640-11e6-8602-328c650afe52.png)

In opera the buttons for login dont work, and the same in chrome:

![captura de pantalla 2016-08-17 a las 13 23 48](https://cloud.githubusercontent.com/assets/11675323/17827321/8425e244-6640-11e6-8f11-12265448e098.png)

And whit the new source code grunt serve run normally, but grunt build show one error:

![captura de pantalla 2016-08-17 a las 13 26 07](https://cloud.githubusercontent.com/assets/11675323/17827329/a53949da-6640-11e6-9c6e-33b4126137fd.png)

And the page stay charging (the same in opera and chrome) and show this errors:

![captura de pantalla 2016-08-17 a las 13 27 03](https://cloud.githubusercontent.com/assets/11675323/17827339/c9269690-6640-11e6-9bf2-d630dbdfed35.png)

Thanks.
Roberto Carlos Carrillo Figueroa

**Comment by Vladlukhanin** [comment]
For the first case (Where the app is personalized) - https://github.com/amatosc/CryptoJS and change path for CryptoJS (like this https://gyazo.com/b482c76bb92a2dedd46f768658ddd274). This was because Google removed the old link for CryptoJS.

For the second case - removed string **"quickblox": "^2.1.1",** from bower.json (../q-municate-web/bower.json) and run **bower install** again. While for qmunicate we use a separate branch of our repository sdk (the path for sdk  is existing in another file)

**Comment by Loborro** [comment]
It works, thanks.
