### ISSUE TITLE
Global Search

### ISSUE THREAD

**Issue by ulamnet** [QuickBlox/q-municate-web#81]
Hello , ı install q-web but global search doesnt work. How to fix ?

thanks.

**Comment by Vladlukhanin** [comment]
Hello, @ulamnet 

Could you provide more information (version of the Qmunicate, errors in the console or something else)?

**Comment by ulamnet** [comment]
version : 1.6.2 you can try demo : http://siwip.com/

**Comment by Vladlukhanin** [comment]
Thanks for the information, now it's your problem is clear. You must enable the permissions for recieve information about users. Here is the solution: https://gyazo.com/2c8b652f8902191e4a335d38cab7c183 (for your admin panel)

**Comment by ulamnet** [comment]
Okay now fixed. But now user video and voice calls doesnt work.

**Comment by Vladlukhanin** [comment]
Give us detailed information about your issue.

**Comment by ulamnet** [comment]
When ı call to my friend , video call don't send . Sorry my bad english.

![when](https://cloud.githubusercontent.com/assets/583003/17773292/6a4e4f04-6556-11e6-81dc-4187fbd3e10b.PNG)

**Comment by Vladlukhanin** [comment]
I can't see that your friend is online.

**Comment by ulamnet** [comment]
See . I see Just connect... text and connection not closed.

![see2](https://cloud.githubusercontent.com/assets/583003/17774273/979dfdc4-655b-11e6-96c8-478829fb360c.PNG)

**Comment by Vladlukhanin** [comment]
You need to run your website on a secure **https** protocol instead of **http** for working webRTC

**Comment by ulamnet** [comment]
I need a ssl certifacete , right ?

**Comment by Vladlukhanin** [comment]
Right )

**Comment by ulamnet** [comment]
okay , thanks.

**Comment by Vladlukhanin** [comment]
Good luck!

**Comment by Vladlukhanin** [comment]
Hi, @ulamnet ! 

Now everything is working? Can I close issue?

**Comment by Lexoan** [comment]
Hi Vlad! am interested in integrating quickblox to my live app. I need to hire a developer. Pls how do I go about this?

**Comment by Vladlukhanin** [comment]
Hi, @Lexoan 

You can't hire our developer. We only support the our product.

See here that would get more information:
http://quickblox.com/contact/
http://quickblox.com/enterprise/

**Comment by Lexoan** [comment]
Thanks Vlad,

for your courteous response. I was not thinking of hiring your developer
but that you would be kind enough to refer me to a developer that is
skilled at using your product. Afterall, it is to your company's gain that
we employ your product successfully.

Looking forward to your kind support
