### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by EminDemiri** [QuickBlox/q-municate-web#83]
I'm trying to install q-municate on my server but when I go 'npm install' I get this error: 
`npm WARN package.json q-municate @ No repository field.`

What should I do?

**Comment by Vladlukhanin** [comment]
It doesn't affect the app work (simple warning), but we will update the file patskage.json in next release (1.7.0).

In _.../q-municate-web/package.json_ need to add this fields:

```
    ...
    "repository": {
        "type": "git",
        "url": "git@github.com:QuickBlox/q-municate-web.git"
    },
    "license" : "(Apache-2.0)",
    ...
```

https://github.com/QuickBlox/q-municate-web/blob/develop/package.json

**Comment by EminDemiri** [comment]
I added the code you gave me but now when you run 'npm install' nothing happens

This is my package.json file  : 
`{
    "name": "q-municate",
    "version": "1.6.2",
    "repository": {
        "type": "git",
        "url": "git@github.com:QuickBlox/q-municate-web.git"
    },
    "license" : "(Apache-2.0)",
    "dependencies": {},
    "devDependencies": {
        "connect-livereload": "^0.5.4",
        "ghooks": "^1.2.1",
        "grunt": "^0.4.0",
        "grunt-bower-requirejs": "^2.0.0",
        "grunt-contrib-clean": "^1.0.0",
        "grunt-contrib-compass": "^1.0.4",
        "grunt-contrib-concat": "^1.0.1",
        "grunt-contrib-connect": "^1.0.2",
        "grunt-contrib-copy": "^1.0.0",
        "grunt-contrib-cssmin": "^1.0.1",
        "grunt-contrib-handlebars": "^1.0.0",
        "grunt-contrib-htmlmin": "^1.5.0",
        "grunt-contrib-imagemin": "^1.0.0",
        "grunt-contrib-jshint": "^1.0.0",
        "grunt-contrib-uglify": "^1.0.1",
        "grunt-contrib-watch": "^1.0.0",
        "grunt-include-replace": "^4.0.1",
        "grunt-newer": "^1.1.1",
        "grunt-open": "^0.2.3",
        "grunt-requirejs": "^0.4.2",
        "grunt-rev": "^0.1.0",
        "grunt-usemin": "^3.1.1",
        "jshint-stylish": "^2.1.0",
        "load-grunt-tasks": "^3.3.0",
        "time-grunt": "^1.2.2"
    },
    "scripts": {},
    "engines": {
        "node": ">=4.4.5"
    },
    "config": {
        "ghooks": {
            "pre-push": "grunt test"
        }
    }
}`

**Comment by Vladlukhanin** [comment]
Do you have node_modules folder in your app?

**Comment by EminDemiri** [comment]
I am trying to perform the installation again. I just deleted everything. Now as you install I send the screan

**Comment by Vladlukhanin** [comment]
Most likely the installation was successful, warnings couldn't prevent it. Nothing happens because the node_modules are installed

**Comment by EminDemiri** [comment]
I downloaded and installed all over again now works.
Thank you
