### ISSUE TITLE
Calls and video calls do not work on google chrome

### ISSUE THREAD

**Issue by EminDemiri** [QuickBlox/q-municate-web#85]
I'm doing some tests to verify proper operation of all modules.

On firefox is the call that video call function properly but google chrome not.

This is my console once you click on the call button:

`[Q-MUNICATE debug mode]:
71cf2b13.build.js:6 Error NavigatorUserMediaError {name: "PermissionDeniedError", message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).", constraintName: ""} 71cf2b13.build.js:14

Uncaught TypeError: w.stop is not a function(anonymous function) @ 71cf2b13.build.js:14
dispatch @ 71cf2b13.build.js:4
q.handle @ 71cf2b13.build.js:4
trigger @ 71cf2b13.build.js:4
(anonymous function) @ 71cf2b13.build.js:
4each @ 71cf2b13.build.js:3
each @ 71cf2b13.build.js:3
trigger @ 71cf2b13.build.js:4
_.fn.(anonymous function) @ 71cf2b13.build.js:4
(anonymous function) @ 71cf2b13.build.js:14
(anonymous function) @ 71cf2b13.build.js:7
(anonymous function) @ quickblox.min.js:3
d.getUserMedia @ quickblox.min.js:3
e.getUserMedia @ 71cf2b13.build.js:7
g.startCall @ 71cf2b13.build.js:14
(anonymous function) @ 71cf2b13.build.js:14
dispatch @ 71cf2b13.build.js:4
q.handle @ 71cf2b13.build.js:4`

What should I change to solve this problem?

**Comment by Vladlukhanin** [comment]
Hi, @EminDemiri !

_Error NavigatorUserMediaError {name: "PermissionDeniedError", message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).", constraintName: ""}_

You need to run your website on a secure https protocol instead of http for working webRTC

**Comment by EminDemiri** [comment]
But you can not make some changes in order to use the service without the https protocol?

**Comment by Vladlukhanin** [comment]
WebRTC API will not work without the HTTPS protocol. There are no solutions.
