### ISSUE TITLE
Problem login whit Facebook

### ISSUE THREAD

**Issue by Loborro** [QuickBlox/q-municate-web#87]
Hi, i have a new problem whit login whit facebook, i receive this alert:

![captura de pantalla 2016-09-13 a las 18 02 56](https://cloud.githubusercontent.com/assets/11675323/18494552/5bb5e246-79dc-11e6-831f-af6a78152be7.png)

I try to put this link `http://api.quickblox.com/auth/facebook/callback` in the facebook app adding a new site web in the configuration panel and put de link in the input text, without success. 

I already put in admin panel from my quickblox acount the Facebook App ID and Facebook Secret key.

What is missing?? 

Sincerely
Roberto Carlos

**Comment by Vladlukhanin** [comment]
Hi, @Loborro !
You need to add App Domains in fb app settings (https://gyazo.com/bc5370499ca3381e76ba45f595be359a)
