### ISSUE TITLE
Android video calling is not working properly using q-municate.

### ISSUE THREAD

**Issue by haripriya517** [QuickBlox/q-municate-web#89]
_Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/q-municate-web/issues)_

**Environment details**
_(Operating system, browser information, QM version)_

**Did this work before?**

**Expected behavior**

**Actual behavior**

**Logs**
_(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))_

**Steps to reproduce the behavior**

**Any others comments?**

**Comment by dimaspirit** [comment]
Fill the issue form correctly.

**Comment by Vladlukhanin** [comment]
Hi, @haripriya517 
Android video calling is not working properly using q-municate - It can be a problem for android qmunicate? (https://github.com/QuickBlox/q-municate-android/issues)
