### ISSUE TITLE
Problems whit quickblox.min.js library.

### ISSUE THREAD

**Issue by Loborro** [QuickBlox/q-municate-web#98]
Hi agains, there some problems whit quickblox.min.js, this is what i get to the console:

![captura de pantalla 2017-01-23 a las 21 41 14](https://cloud.githubusercontent.com/assets/11675323/22233260/c572c330-e1b4-11e6-8517-15594a1a136e.png)

What i need to do?

**Comment by Vladlukhanin** [comment]
Hi! It's old path to QuickBlox sdk. You can update Q-municate or change path to sdk [here](https://github.com/QuickBlox/q-municate-web/blob/master/app/scripts/main.js#L47), for your version of Q-municate is better suited quickblox sdk v.2.1.5 (https://cdnjs.cloudflare.com/ajax/libs/quickblox/2.1.5/quickblox.min.js) instead v.2.5.0.

**Comment by Vladlukhanin** [comment]
@Loborro , did it help you? Can I close issue?

**Comment by Loborro** [comment]
Yeah, this help me a lot, Thanks.
